### ISSUE TITLE
Doesn't run for me on Darwin/SBCL

### ISSUE THREAD

**Issue by quicklisp** [borodust/trivial-gamekit#15] opened 2017-11-29 13:13 UTC
When I try `(gamekit:start 'example)`, I get this.

I get this in the debugger:

    FLOATING-POINT-OVERFLOW: arithmetic error FLOATING-POINT-OVERFLOW signalled
       [Condition of type SIMPLE-CONDITION]

    Restarts:
     0: [CONTINUE] Return from BREAK.
     1: [CONTINUE] Skip flow block returning nil
     2: [USE-VALUE] Skip flow block returning provided value
     3: [STOP] Stop the task.
     4: [SKIP] Skip running #<CALL-TASK :FUNC #<CLOSURE (LAMBDA () :IN CL-BODGE.ENGINE:INITIALIZE-SYSTEM) {10060E923B}> :STATUS :RUNNING {100616C3A3}>
     5: [ABORT] Stop the runner #<QUEUED-RUNNER :STATUS :RUNNING {1003839453}> entirely.
     --more--

    Backtrace:
      0: ("bogus stack frame")
      1: ("foreign function: -[CALayer setNeedsDisplayInRect:]")
      2: ("foreign function: _NSBackingLayerSetNeedsDisplayInRect")
      3: ("foreign function: -[_NSBackingLayer setNeedsDisplayInRect:]")
      4: ("foreign function: -[CALayer setNeedsDisplay]")
      5: ("foreign function: -[NSTextFieldCell _invalidateTextLayerIfNeeded]")
      6: ("foreign function: -[NSTextFieldCell setObjectValue:]")
      7: ("foreign function: -[NSCell setAttributedStringValue:]")
      8: ("foreign function: -[NSControl setAttributedStringValue:]")
      9: ("foreign function: -[NSTextField setAttributedStringValue:]")
     10: ("foreign function: -[NSThemeFrame updateTitleTextField]")
     11: ("foreign function: -[NSThemeFrame setTitle:]")
     12: ("foreign function: -[NSWindow _dosetTitle:andDefeatWrap:]")
     13: (%CL-GLFW3:SET-WINDOW-TITLE #.(SB-SYS:INT-SAP #X0053D4B0) "Trivial Gamekit")
     14: ((LABELS #:DISPATCHED11 :IN CL-BODGE.ENGINE:INITIALIZE-SYSTEM))
     15: ((FLET CL-BODGE.CONCURRENCY::WRAPPED :IN CL-BODGE.CONCURRENCY:DISPATCH))
     16: ((FLET CL-BODGE.CONCURRENCY::WRAPPED :IN CL-BODGE.CONCURRENCY:DISPATCH))
     17: (CL-BODGE.CONCURRENCY:DRAIN #S(CL-BODGE.CONCURRENCY::TASK-QUEUE :QUEUE #<CL-MUTH::GUARDED-REFERENCE {100605B263}>) NIL)
     18: (DISSECT::STACK-TRUNCATOR #<CLOSURE DISSECT::WITH-TRUNCATED-STACK-LAMBDA {1005AB6C1B}>)
     19: (DISSECT::WITH-TRUNCATED-STACK-LAMBDA)

I get this in the REPL:

    <ERROR> [08:09:07] cl-bodge.host system.lisp (initialize-system :after host-system with-truncated-stack-lambda h1) -
      Unhandled error:
    arithmetic error FLOATING-POINT-OVERFLOW signalled
       [Condition of type FLOATING-POINT-OVERFLOW]

    #<ENVIRONMENT {1006194E13}>
       [Environment of thread #<THREAD "main thread" RUNNING {1001BA1293}>]

    Available restarts:
     0: [CONTINUE] Skip flow block returning nil
     1: [USE-VALUE] Skip flow block returning provided value
     2: [STOP] Stop the task.
     3: [SKIP] Skip running #<CALL-TASK :FUNC #<CLOSURE (LAMBDA ()
					       :IN
					       CL-BODGE.ENGINE:INITIALIZE-SYSTEM) {10060E923B}> :STATUS :RUNNING {100616C3A3}>
     4: [ABORT] Stop the runner #<QUEUED-RUNNER :STATUS :RUNNING {1003839453}> entirely.
     5: [STOP-RUNNER] Stop the runner #<QUEUED-RUNNER :STATUS :RUNNING {1003839453}> entirely.
     6: [ABORT] Exit debugger, returning to top level.

    Backtrace:
     7: (SB-KERNEL::%SIGNAL arithmetic error FLOATING-POINT-OVERFLOW signalled)
     8: (ERROR FLOATING-POINT-OVERFLOW OPERATION NIL OPERANDS NIL)
     9: (SB-VM:SIGFPE-HANDLER #<unused argument> #.(SB-SYS:INT-SAP #X019FD680) #.(SB-SYS:INT-SAP #X019FD6E8))
     10: ((FLET "WITHOUT-INTERRUPTS-BODY-8" :IN SB-SYS:INVOKE-INTERRUPTION))
     11: ((FLET SB-THREAD::EXEC :IN SB-SYS:INVOKE-INTERRUPTION))
     12: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-SYS:INVOKE-INTERRUPTION))
     13: ((FLET SB-UNIX::RUN-HANDLER :IN SB-SYS:ENABLE-INTERRUPT) 8 #.(SB-SYS:INT-SAP #X019FD680) #.(SB-SYS:INT-SAP #X019FD6E8))
     14: ("foreign function: call_into_lisp")
     15: ("foreign function: funcall3")
     16: ("foreign function: interrupt_handle_now")
     17: ("foreign function: low_level_handle_now_handler")
     18: ("foreign function: _sigtramp")
     19: ("bogus stack frame")
     20: ("foreign function: -[CALayer setNeedsDisplayInRect:]")
     21: ("foreign function: _NSBackingLayerSetNeedsDisplayInRect")
     22: ("foreign function: -[_NSBackingLayer setNeedsDisplayInRect:]")
     23: ("foreign function: -[CALayer setNeedsDisplay]")
     24: ("foreign function: -[NSTextFieldCell _invalidateTextLayerIfNeeded]")
     25: ("foreign function: -[NSTextFieldCell setObjectValue:]")
     26: ("foreign function: -[NSCell setAttributedStringValue:]")
     27: ("foreign function: -[NSControl setAttributedStringValue:]")
     28: ("foreign function: -[NSTextField setAttributedStringValue:]")
     29: ("foreign function: -[NSThemeFrame updateTitleTextField]")
     30: ("foreign function: -[NSThemeFrame setTitle:]")
     31: ("foreign function: -[NSWindow _dosetTitle:andDefeatWrap:]")
     32: (%CL-GLFW3:SET-WINDOW-TITLE #.(SB-SYS:INT-SAP #X0053D4B0) Trivial Gamekit)
     33: ((LABELS #:DISPATCHED11 :IN CL-BODGE.ENGINE:INITIALIZE-SYSTEM))
     34: ((FLET CL-BODGE.CONCURRENCY::WRAPPED :IN CL-BODGE.CONCURRENCY:DISPATCH))
     35: ((FLET CL-BODGE.CONCURRENCY::WRAPPED :IN CL-BODGE.CONCURRENCY:DISPATCH))
     36: (CL-BODGE.CONCURRENCY:DRAIN #S(CL-BODGE.CONCURRENCY::TASK-QUEUE :QUEUE #<GUARDED-REFERENCE {100605B263}>) NIL)
    NIL

The REPL output seems to be from a different thread, as I can't interact with the debugger there.

I'm using this:

    CL-USER> (lisp-implementation-version)
    "1.4.1.220-f2f0f53e6"

    $ uname -a
    Darwin graybar 16.7.0 Darwin Kernel Version 16.7.0: Wed Oct  4 00:17:00 PDT 2017; root:xnu-3789.71.6~1/RELEASE_X86_64 x86_64

**Comment by borodust** [comment] 2017-12-02 10:21
Thanks for the report! I'll take a look today.

**Comment by borodust** [comment] 2017-12-02 15:58
I've updated `org.borodust.bodge` dist to latest `trivial-gamekit` version. Unfortunately, I couldn't reproduce the issue with it. Can you check if latest version works for you? 

My test configuration:
```
* (lisp-implementation-version)
"1.4.2"

 $ uname -a
Darwin graybar 16.7.0 Darwin Kernel Version 16.7.0: Wed Oct  4 00:17:00 PDT 2017; root:xnu-3789.71.6~1/RELEASE_X86_64 x86_64
```

**Comment by quicklisp** [comment] 2017-12-02 16:54
I switched to SBCL 1.4.2 and updated the dist, but I'm afraid the same error persists.

**Comment by borodust** [comment] 2017-12-02 17:30
Apparently, this is the same error as in #4

**Comment by borodust** [comment] 2017-12-02 18:50
I think i found the [culprit](https://github.com/borodust/cl-bodge/commit/2d47f61b8c6646a2496ef3d75e5824fe0648fed6) and updated `org.borodust.bodge` dist. Please, replace the dist with newer version and try the example again to see if the issue is still persist for you.

**Comment by borodust** [comment] 2017-12-06 14:09
It even works on fresh High Sierra install on MBP mid-2012... sigh
Search continues.

**Comment by borodust** [comment] 2017-12-06 18:21
Fixed in https://github.com/borodust/cl-bodge/commit/c42b7f9b7672dc763f308d95ef974b26792c0c4e

**Comment by borodust** [comment] 2017-12-06 21:12
Actually, nope! Repeats when setting a viewport size. Need to mask FPE there as well.

**Comment by borodust** [comment] 2017-12-07 06:31
Fixed in https://github.com/borodust/cl-bodge/commit/8288bf6999f343fc356b92ae30620ae0fd32cbf5

**Closed by borodust** 2017-12-07 06:31 UTC
